Set Height 900
Source '/vhs/.scripts/gifs/base.tape'

Output '.scripts/gifs/commit.gif'

Hide
Type 'echo "demo commit change" >> README.md'
Enter
Type 'git add README.md'
Enter
Type 'clear'
Enter
Show
Type 'pair commit'
Enter
Sleep 0.8s
Down 2
Sleep 0.4s
Enter
Sleep 0.4s
Type '456'
Sleep 0.4s
Enter
Sleep 0.5s
Space
Down
Space
Sleep 0.5s
Enter
Sleep 0.5s
Type 'pair commits are easy'
Enter
Sleep 2s
