Set Height 900
Source '/vhs/.scripts/gifs/base.tape'

Output '.scripts/gifs/overview.gif'

Hide
Type 'echo "demo commit change" >> README.md'
Enter
Type 'git add README.md'
Enter
Type 'clear'
Enter
Show
Type 'pair --help'
Enter
Sleep 1.4s
Type 'pair on 666'
Enter
Sleep 0.8s
Type 'pair with'
Enter
Sleep 0.5s
Space
Down
Space
Sleep 0.8s
Enter
Type 'pair commit'
Enter
Sleep 0.3s
Down
Space
Enter
Sleep 0.4s
Type 'pair commits made easy'
Enter
Sleep 2s
