#!/usr/bin/expect -f

set env(ACCESSIBLE) true
set timeout 10
spawn pair commit
match_max 100000
expect -re {.*Enter a number between [0-9]+ and [0-9]+: }
send -- "1\r"
expect -re {.*enter ticket ID:.*}
send -- "PROMPT-123\r"
expect -re {.*Enter a number between 0 and [0-9]+: }
send -- "1\r"
expect -re {.*Enter a number between 0 and [0-9]+: }
send -- "0\r"
expect -re {.*edit commit message:.*}
send -- "test commit message\r"
expect eof
set result [wait]
exit [lindex $result 3]
